services:
  - type: web
    name: imposter-game
    env: node
    buildCommand: npm install && cd client && npm install --legacy-peer-deps && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production 